/**
 * Berserker — pain into power.
 *
 * The pilot for: **Rage** generated by *taking* damage (not kills), decaying out of
 * combat; **Bleed** as a physical DoT that stacks, spreads and detonates; health spent
 * as a resource (Blood Price, Deathblow); the `guardsDeath` status (Last Stand); and
 * caster-missing-health damage scaling (Last Breath, Worldbreaker).
 *
 * Question: how much pain can I turn into power?
 */

import type { Ability } from "../combat/ability";
import type { ResourceSpec } from "../combat/resources";
import type { StatusSpec } from "../combat/status";
import type { ClassProgression } from "./nodes";
import type { PathUnlockDef } from "./unlocks";
import type { PilotClass } from "./class";

// --- resources ----------------------------------------------------------

export const BERSERKER_RAGE: ResourceSpec = {
  id: "rage",
  label: "Rage",
  max: 100,
  start: "empty",
  ui: "bar",
  decayPerSec: 6,
  decayDelay: 4,
  healthConversion: { ratio: 2 },
  generation: [
    { on: "damageTaken", amount: 45, perUnit: "maxHealthFraction" },
    { on: "hitDealt", amount: 2, requireTags: ["melee"] },
    { on: "ailmentInflicted", amount: 3, requireTags: ["bleed"] },
    { on: "kill", amount: 8 },
  ],
  thresholds: [
    { at: 40, whileAbove: { attackSpeed: 0.12, meleeDamage: 0.08 } },
    { at: 80, onCross: "berserker.seeing_red", whileAbove: { attackSpeed: 0.2, meleeDamage: 0.18, moveSpeed: 0.08 } },
  ],
};

/** The Berserker earns the ultimate the way the class wants to be played: by bleeding for it. */
export const BERSERKER_ULTIMATE_METER: ResourceSpec = {
  id: "ultimate",
  label: "Worldbreaker",
  max: 100,
  start: "empty",
  ui: "meter",
  isUltimateMeter: true,
  generation: [
    { on: "damageTaken", amount: 60, perUnit: "maxHealthFraction" },
    { on: "hitDealt", amount: 1.5, requireTags: ["heavy"] },
  ],
};

export const BERSERKER_RESOURCES: readonly ResourceSpec[] = [BERSERKER_RAGE, BERSERKER_ULTIMATE_METER];

// --- statuses ---------------------------------------------------------

/** Frenzy — Frenzy Chain's stacking self-buff: each hit on the same body makes the next faster. */
export const STATUS_FRENZY: StatusSpec = {
  id: "frenzy",
  label: "Frenzy",
  glyph: "f",
  category: "buff",
  tags: ["melee"],
  baseDuration: 3,
  maxStacks: 6,
  refreshRule: "refresh",
  mods: { attackSpeed: 0.06, meleeDamage: 0.04 },
};

/** Last Stand — the Berserker cannot be killed for a moment, but cannot be healed either. */
export const STATUS_LAST_STAND: StatusSpec = {
  id: "last_stand",
  label: "Last Stand",
  glyph: "L",
  category: "buff",
  baseDuration: 4,
  maxStacks: 1,
  refreshRule: "refresh",
  guardsDeath: true,
  unremovable: true,
};

/** Butcher's high — kills widen the swing for a few seconds. */
export const STATUS_BUTCHER: StatusSpec = {
  id: "butcher",
  label: "Butcher's Momentum",
  glyph: "B",
  category: "buff",
  baseDuration: 5,
  maxStacks: 3,
  refreshRule: "refresh",
  mods: { areaSize: 0.1, meleeDamage: 0.06 },
};

export const BERSERKER_STATUSES: readonly StatusSpec[] = [STATUS_FRENZY, STATUS_LAST_STAND, STATUS_BUTCHER];

// --- abilities (9 + 1) ------------------------------------------------

export const BERSERKER_SKULLBREAKER: Ability = {
  id: "berserker.skullbreaker",
  classId: "berserker",
  name: "Skullbreaker",
  description: "An overhead axe strike that comes down on one body with enough force to stagger an elite.",
  flavor: "Everything below the collarbone is a formality.",
  category: "attack",
  tags: ["melee", "heavy", "slash", "interrupt"],
  costs: [{ resource: "rage", amount: 15 }],
  cooldown: 5,
  castTime: 0.35,
  targeting: "enemy",
  range: 70,
  effects: [
    { kind: "damage", damage: { base: 3.4, scale: "attack", type: "physical", canCrit: true, knockback: 30 }, to: "target" },
    { kind: "status", status: "stunned", chance: 0.9, to: "target" },
  ],
  mutationHooks: [{ id: "skullbreaker.packet", kind: "damagePacket", note: "Marauder scales the overhead and adds overkill." }],
};

export const BERSERKER_BLOOD_PRICE: Ability = {
  id: "berserker.blood_price",
  classId: "berserker",
  name: "Blood Price",
  description: "Open your own veins for a surge of Rage and attack speed.",
  flavor: "The exchange rate is bad. Take it anyway.",
  category: "utility",
  tags: ["resourceGenerator"],
  cooldown: 8,
  targeting: "self",
  effects: [
    { kind: "damage", damage: { base: 0.18, scale: "flat", type: "physical", channel: "environmental" }, to: "self" },
    { kind: "resource", resource: "rage", delta: 45, to: "self" },
    { kind: "status", status: "frenzy", to: "self", stacks: 3, chance: 1 },
  ],
  mutationHooks: [{ id: "blood_price.gain", kind: "resource", note: "Last Breath makes the trade far more generous below half health." }],
};

export const BERSERKER_FRENZY_CHAIN: Ability = {
  id: "berserker.frenzy_chain",
  classId: "berserker",
  name: "Frenzy Chain",
  description: "A flurry into one target. Every hit that connects makes the next one faster.",
  flavor: "Momentum is just anger with a direction.",
  category: "attack",
  tags: ["melee", "slash", "bleed"],
  cooldown: 3,
  targeting: "enemy",
  range: 60,
  channel: { duration: 1, ticks: 4 },
  effects: [
    { kind: "damage", damage: { base: 0.7, scale: "attack", type: "physical", canCrit: true, inflict: { status: "bleed", chance: 0.5 } }, to: "target" },
    { kind: "status", status: "frenzy", to: "self", chance: 1 },
  ],
};

export const BERSERKER_AXEQUAKE: Ability = {
  id: "berserker.axequake",
  classId: "berserker",
  name: "Axequake",
  description: "Bury the axe in the ground and send a fan of widening cracks forward.",
  flavor: "The floor was load-bearing. It is not any more.",
  category: "attack",
  tags: ["melee", "heavy", "area", "line", "crowdControl"],
  costs: [{ resource: "rage", amount: 20 }],
  cooldown: 9,
  targeting: "cone",
  range: 180,
  shape: { length: 180, arc: Math.PI / 3 },
  telegraph: { shape: "cone", windup: 0.3, arc: Math.PI / 3 },
  effects: [
    { kind: "damage", damage: { base: 2.0, scale: "attack", type: "physical", canCrit: true }, to: "allTargets" },
    { kind: "status", status: "rooted", chance: 0.6, to: "allTargets" },
    { kind: "zone", zone: { radius: 100, duration: 3, tickInterval: 0.5, follows: false, mergeable: true, damage: { base: 0.3, scale: "attack", type: "physical", channel: "periodic" } } },
  ],
};

export const BERSERKER_SAVAGE_GRIP: Ability = {
  id: "berserker.savage_grip",
  classId: "berserker",
  name: "Savage Grip",
  description: "Grab one enemy and hurl it into another, both worse for the meeting.",
  flavor: "Introductions.",
  category: "attack",
  tags: ["melee", "crowdControl"],
  cooldown: 8,
  targeting: "enemy",
  range: 80,
  effects: [
    { kind: "pull", force: 60, to: "target" },
    { kind: "damage", damage: { base: 2.2, scale: "attack", type: "physical", canCrit: true, knockback: 140 }, to: "target" },
    { kind: "status", status: "exposed", chance: 1, to: "target" },
  ],
};

export const BERSERKER_CRIMSON_HOWL: Ability = {
  id: "berserker.crimson_howl",
  classId: "berserker",
  name: "Crimson Howl",
  description: "A roar that hardens your hide and drags every nearby enemy's attention onto you.",
  flavor: "Look at me. Only me.",
  category: "support",
  tags: ["taunt", "threat", "aura"],
  cooldown: 16,
  targeting: "self",
  shape: { radius: 160 },
  effects: [
    { kind: "threat", op: "taunt", radius: 160, to: "enemies" },
    { kind: "shield", amount: 1.2, scale: "attack", to: "self", duration: 6 },
    { kind: "status", status: "weakened", chance: 1, to: "enemies" },
  ],
};

export const BERSERKER_CLEAVERS_REPRISAL: Ability = {
  id: "berserker.cleavers_reprisal",
  classId: "berserker",
  name: "Cleaver's Reprisal",
  description: "Set your stance. The next heavy blow you take primes an automatic counter-swing.",
  flavor: "Hit me. See what happens.",
  category: "support",
  tags: ["counter", "melee"],
  cooldown: 12,
  targeting: "self",
  effects: [
    {
      kind: "reactive",
      event: "damageTaken",
      window: 5,
      effects: [
        { kind: "damage", damage: { base: 2.6, scale: "attack", type: "physical", channel: "retaliation", canCrit: true }, to: "enemies" },
        { kind: "status", status: "bleed", chance: 1, to: "enemies" },
      ],
    },
  ],
};

export const BERSERKER_LAST_STAND: Ability = {
  id: "berserker.last_stand",
  classId: "berserker",
  name: "Last Stand",
  description: "For a few seconds you cannot be brought below 1 HP — and cannot be healed. Spend them.",
  flavor: "Dying is a scheduling problem.",
  category: "support",
  tags: ["barrier"],
  cooldown: 45,
  targeting: "self",
  effects: [{ kind: "status", status: "last_stand", to: "self", chance: 1 }],
  mutationHooks: [{ id: "last_stand.window", kind: "status", note: "Deathwish lengthens the window and adds damage while it holds." }],
};

export const BERSERKER_BUTCHERS_MOMENTUM: Ability = {
  id: "berserker.butchers_momentum",
  classId: "berserker",
  name: "Butcher's Momentum",
  description: "Prime yourself: for a while after your next kills, your swings reach further and land wider.",
  flavor: "Practice makes the arc.",
  category: "utility",
  tags: ["resourceGenerator"],
  cooldown: 20,
  targeting: "self",
  effects: [
    {
      kind: "reactive",
      event: "kill",
      window: 12,
      effects: [{ kind: "status", status: "butcher", to: "self", chance: 1 }],
    },
  ],
};

export const BERSERKER_WORLDBREAKER: Ability = {
  id: "berserker.worldbreaker",
  classId: "berserker",
  name: "Worldbreaker",
  description: "An escalating sequence of enormous axe strikes, ending in a shockwave that hits harder the closer you are to death.",
  flavor: "The last swing is the honest one.",
  category: "ultimate",
  tags: ["ultimate", "melee", "heavy", "area", "nova"],
  cooldown: 0,
  isUltimate: true,
  targeting: "radius",
  range: 160,
  fx: { travel: "lance" },
  shape: { radius: 160 },
  effects: [
    { kind: "damage", damage: { base: 3, scale: "attack", type: "physical", canCrit: true }, to: "allTargets" },
    { kind: "delay", seconds: 0.5, effects: [{ kind: "damage", damage: { base: 4, scale: "attack", type: "physical", canCrit: true }, to: "allTargets" }] },
    {
      kind: "delay",
      seconds: 1.1,
      effects: [
        { kind: "damage", damage: { base: 6, scale: "attack", type: "physical", canCrit: true, casterMissingHealth: 1.5, knockback: 200 }, to: "allTargets" },
        { kind: "status", status: "bleed", chance: 1, stacks: 3, to: "allTargets" },
      ],
    },
  ],
  mutationHooks: [{ id: "worldbreaker.finale", kind: "followUp", note: "Blood God turns the finale into a standing aura while near death." }],
};

export const BERSERKER_ABILITIES: readonly Ability[] = [
  BERSERKER_SKULLBREAKER,
  BERSERKER_BLOOD_PRICE,
  BERSERKER_FRENZY_CHAIN,
  BERSERKER_AXEQUAKE,
  BERSERKER_SAVAGE_GRIP,
  BERSERKER_CRIMSON_HOWL,
  BERSERKER_CLEAVERS_REPRISAL,
  BERSERKER_LAST_STAND,
  BERSERKER_BUTCHERS_MOMENTUM,
  BERSERKER_WORLDBREAKER,
];

// --- the tree -------------------------------------------------------

export const BERSERKER_PROGRESSION: ClassProgression = {
  classId: "berserker",
  paths: [
    // 0 — Bloodletter: Bleed generates Rage, spreads, and detonates on kills.
    {
      name: "Bloodletter",
      blurb: "Bleed stacks generate Rage, spread, and explode when the body drops.",
      nodes: [
        {
          name: "Fresh Wound",
          blurb: "Every melee hit has a real chance to open a bleed.",
          category: "foundation",
          effects: [
            { kind: "mods", mods: { ailmentChance: 0.15, meleeDamage: 0.05 } },
            {
              kind: "grantEffect",
              on: { tag: "melee" },
              effects: [{ kind: "status", status: "bleed", chance: 0.35, to: "allTargets" }],
            },
          ],
        },
        {
          name: "Open Artery",
          blurb: "Bleeds you apply stack deeper and tick harder.",
          category: "behavior",
          effects: [
            {
              kind: "mutate",
              mutation: {
                id: "bloodletter.open_artery",
                label: "bleeds run deeper",
                target: { withTag: "bleed" },
                ops: [{ kind: "status", scaleDuration: 1.3, addStacks: 1 }],
              },
            },
          ],
        },
        {
          name: "Blood Frenzy",
          blurb: "Bleeding enemies feed your Rage every time they tick.",
          category: "resource",
          effects: [
            {
              kind: "resourceRule",
              resource: "rage",
              patch: { addGeneration: [{ on: "ailmentInflicted", amount: 5, requireTags: ["bleed"] }] },
            },
          ],
        },
        {
          name: "Paint the Room",
          blurb: "Frenzy Chain flings blood: its bleed leaps to a second nearby body.",
          category: "mutation",
          effects: [
            {
              kind: "mutate",
              mutation: {
                id: "bloodletter.paint_the_room",
                label: "Frenzy Chain → Paint the Room",
                target: { abilityId: "berserker.frenzy_chain" },
                ops: [
                  { kind: "addEffect", at: "end", effects: [{ kind: "spreadStatus", status: "bleed", radius: 90, to: "target" }] },
                  { kind: "addTags", tags: ["area"] },
                ],
              },
            },
          ],
        },
        {
          name: "Crimson Avalanche",
          blurb: "An enemy that dies while bleeding bursts, spreading and re-applying every stack around it.",
          category: "keystone",
          effects: [
            { kind: "rule", rule: "berserker.bloodletter.crimson_avalanche" },
            {
              kind: "grantEffect",
              on: { event: "enemyDeath" },
              effects: [{ kind: "spreadStatus", status: "bleed", radius: 130, to: "target" }],
            },
          ],
        },
      ],
    },

    // 1 — Last Breath: lower health, higher output.
    {
      name: "Last Breath",
      blurb: "The closer to death you fight, the harder you hit and the less anything can stop you.",
      nodes: [
        {
          name: "Pain Tolerance",
          blurb: "Damage below half health is blunted, and your hits grow with the wound.",
          category: "foundation",
          effects: [{ kind: "mods", mods: { defensePercent: 0.08, meleeDamage: 0.06 } }],
        },
        {
          name: "Danger Zone",
          blurb: "Under a third health, cooldowns come back faster and knockback washes off you.",
          category: "behavior",
          effects: [{ kind: "rule", rule: "berserker.lastbreath.danger_zone", note: "Low-health threshold flips a mobility/mitigation rule." }],
        },
        {
          name: "Near Death",
          blurb: "Missing health is Rage in reserve — the emptier the bar, the faster it fills.",
          category: "resource",
          effects: [
            {
              kind: "resourceRule",
              resource: "rage",
              patch: { addGeneration: [{ on: "damageTaken", amount: 30, perUnit: "maxHealthFraction" }] },
            },
          ],
        },
        {
          name: "Refuse",
          blurb: "Skullbreaker and Worldbreaker scale off your own missing health.",
          category: "mutation",
          effects: [
            {
              kind: "mutate",
              mutation: {
                id: "lastbreath.refuse",
                label: "heavy strikes read your wounds",
                target: { withAllTags: ["melee", "heavy"] },
                ops: [{ kind: "damagePacket", scaleBase: 1.05 }],
              },
            },
          ],
        },
        {
          name: "Deathwish",
          blurb: "Last Stand lasts longer and, while it holds, every hit you land is a critical.",
          category: "keystone",
          effects: [
            { kind: "rule", rule: "berserker.lastbreath.deathwish" },
            {
              kind: "mutate",
              mutation: {
                id: "lastbreath.deathwish",
                label: "Last Stand → Deathwish",
                target: { abilityId: "berserker.last_stand" },
                ops: [
                  { kind: "status", scaleDuration: 1.75 },
                  { kind: "trigger", event: "hit", window: 6, effects: [{ kind: "damage", damage: { base: 0.6, scale: "attack", type: "physical", channel: "retaliation" }, to: "enemies" }] },
                ],
              },
            },
          ],
        },
      ],
    },

    // 2 — Marauder: enormous physical attacks and overkill shockwaves.
    {
      name: "Marauder",
      blurb: "Everything gets bigger. Overkill damage doesn't go to waste — it goes outward.",
      nodes: [
        {
          name: "Heavy Grip",
          blurb: "Heavy skills hit a wider area and shove harder.",
          category: "foundation",
          effects: [
            { kind: "mods", mods: { areaSize: 0.12 } },
            {
              kind: "mutate",
              mutation: {
                id: "marauder.heavy_grip",
                label: "heavy skills widen",
                target: { withTag: "heavy" },
                ops: [{ kind: "targeting", scaleArc: 1.2, scaleRadius: 1.2, scaleLength: 1.15 }],
              },
            },
          ],
        },
        {
          name: "Bone Breaker",
          blurb: "Your stuns and staggers last noticeably longer.",
          category: "behavior",
          effects: [
            {
              kind: "mutate",
              mutation: {
                id: "marauder.bone_breaker",
                label: "control lingers",
                target: { withTag: "crowdControl" },
                ops: [{ kind: "status", scaleDuration: 1.4 }],
              },
            },
          ],
        },
        {
          name: "Overkill",
          blurb: "Damage dealt past a kill is stored, then spent on the next heavy swing.",
          category: "resource",
          effects: [
            { kind: "rule", rule: "berserker.marauder.overkill" },
            {
              kind: "resourceRule",
              resource: "rage",
              patch: { addGeneration: [{ on: "enemyDeath", amount: 6 }] },
            },
          ],
        },
        {
          name: "Giant Swing",
          blurb: "Skullbreaker becomes a full spin: it hits everything in reach, not one body.",
          category: "mutation",
          effects: [
            {
              kind: "mutate",
              mutation: {
                id: "marauder.giant_swing",
                label: "Skullbreaker → Giant Swing",
                target: { abilityId: "berserker.skullbreaker" },
                ops: [
                  { kind: "targeting", setMode: "radius" },
                  { kind: "damagePacket", scaleBase: 0.8 },
                  { kind: "addTags", tags: ["area"] },
                ],
              },
            },
          ],
        },
        {
          name: "World-Eater",
          blurb: "Every kill releases a physical shockwave scaled by how badly you overkilled it.",
          category: "keystone",
          effects: [
            { kind: "rule", rule: "berserker.marauder.world_eater" },
            {
              kind: "grantEffect",
              on: { event: "kill" },
              effects: [{ kind: "damage", damage: { base: 1.4, scale: "attack", type: "physical", channel: "execute", knockback: 120 }, to: "enemies" }],
            },
          ],
        },
      ],
    },

    // 3 — Inferno: fire zones, explosions, and an aura powered by Rage.
    {
      name: "Inferno",
      blurb: "Rage burns. Your weapon carries fire, your kills leave craters, and at high Rage you radiate it.",
      nodes: [
        {
          name: "Burning Blood",
          blurb: "A slice of your physical damage converts to fire, and your hits can ignite.",
          category: "foundation",
          effects: [
            { kind: "mods", mods: { fireDamage: 0.15 } },
            {
              kind: "grantEffect",
              on: { tag: "melee" },
              effects: [{ kind: "status", status: "burn", chance: 0.3, to: "allTargets" }],
            },
          ],
        },
        {
          name: "Searing Weapon",
          blurb: "Axequake leaves a fire field instead of just cracks.",
          category: "behavior",
          effects: [
            {
              kind: "mutate",
              mutation: {
                id: "inferno.searing_weapon",
                label: "Axequake burns",
                target: { abilityId: "berserker.axequake" },
                ops: [
                  { kind: "zone", scaleDuration: 1.6, setStatus: { id: "burn", chance: 0.8 } },
                  { kind: "damagePacket", setType: "fire" },
                ],
              },
            },
          ],
        },
        {
          name: "Combustion",
          blurb: "Burning enemies you kill detonate, and the blast tops up your Rage.",
          category: "resource",
          effects: [
            {
              kind: "resourceRule",
              resource: "rage",
              patch: { addGeneration: [{ on: "kill", amount: 6, requireTags: ["burn"] }] },
            },
            {
              kind: "grantEffect",
              on: { event: "kill" },
              effects: [{ kind: "consumeStatus", status: "burn", to: "target", then: [{ kind: "damage", damage: { base: 1.2, scale: "attack", type: "fire", channel: "execute" }, to: "enemies" }] }],
            },
          ],
        },
        {
          name: "Wildfire",
          blurb: "Fire zones you create merge and grow instead of overlapping.",
          category: "mutation",
          effects: [
            {
              kind: "mutate",
              mutation: {
                id: "inferno.wildfire",
                label: "fire zones spread",
                target: { withTag: "area" },
                ops: [{ kind: "zone", forceMergeable: true, scaleRadius: 1.15 }],
              },
            },
          ],
        },
        {
          name: "Living Furnace",
          blurb: "Above 80 Rage you burn everything around you, and the aura eats Rage to stay lit.",
          category: "keystone",
          effects: [
            { kind: "rule", rule: "berserker.inferno.living_furnace" },
            {
              kind: "resourceRule",
              resource: "rage",
              patch: { addThresholds: [{ at: 80, whileAbove: { fireDamage: 0.25, elementalDamage: 0.15 } }] },
            },
          ],
        },
      ],
    },

    // 4 — Predator: kill chains improve speed and refund offensive cooldowns.
    {
      name: "Predator",
      blurb: "One kill is a start. The rhythm is the point.",
      nodes: [
        {
          name: "Blood Scent",
          blurb: "You move faster toward wounded enemies and hit them harder.",
          category: "foundation",
          effects: [
            { kind: "mods", mods: { moveSpeed: 0.06 } },
            {
              kind: "mutate",
              mutation: {
                id: "predator.blood_scent",
                label: "hits punish the wounded",
                target: { withTag: "melee" },
                ops: [{ kind: "damagePacket", addExecuteMissingHealth: 0.05 }],
              },
            },
          ],
        },
        {
          name: "Feast",
          blurb: "Kills heal you a little and top up Rage.",
          category: "behavior",
          effects: [
            {
              kind: "grantEffect",
              on: { event: "kill" },
              effects: [
                { kind: "heal", amount: 0.08, scale: "attack", to: "self" },
                { kind: "resource", resource: "rage", delta: 6, to: "self" },
              ],
            },
          ],
        },
        {
          name: "Kill Rhythm",
          blurb: "Each kill inside the window shortens every offensive cooldown.",
          category: "resource",
          effects: [
            { kind: "rule", rule: "berserker.predator.kill_rhythm" },
            {
              kind: "resourceRule",
              resource: "rage",
              patch: { addGeneration: [{ on: "kill", amount: 4 }] },
            },
          ],
        },
        {
          name: "Continuous Violence",
          blurb: "Butcher's Momentum refreshes and stacks higher whenever you keep killing.",
          category: "mutation",
          effects: [
            {
              kind: "mutate",
              mutation: {
                id: "predator.continuous_violence",
                label: "Butcher's Momentum → Continuous Violence",
                target: { abilityId: "berserker.butchers_momentum" },
                ops: [
                  { kind: "trigger", event: "kill", window: 18, effects: [{ kind: "status", status: "butcher", to: "self", chance: 1 }] },
                  { kind: "cooldown", scale: 0.6 },
                ],
              },
            },
          ],
        },
        {
          name: "Carnage Engine",
          blurb: "A kill inside the window fully refunds your last-used skill and extends the window.",
          category: "keystone",
          effects: [{ kind: "rule", rule: "berserker.predator.carnage_engine" }],
        },
      ],
    },
  ],
};

// --- hybrids + archetype -------------------------------------------

export const BERSERKER_UNLOCKS: readonly PathUnlockDef[] = [
  {
    id: "berserker.blood_frenzy",
    classId: "berserker",
    tier: "hybrid",
    name: "Blood Frenzy",
    description: "Bleed stacks and missing health multiply each other's Rage generation instead of just adding.",
    flavor: "The tank is a bucket with a hole. So is the Rage bar.",
    requires: [
      { path: "Bloodletter", points: 3 },
      { path: "Last Breath", points: 2 },
    ],
    effects: [
      { kind: "rule", rule: "berserker.hybrid.blood_frenzy" },
      {
        kind: "resourceRule",
        resource: "rage",
        patch: { addGeneration: [{ on: "ailmentInflicted", amount: 4, requireTags: ["bleed"] }] },
      },
    ],
    ui: { badge: "BFR" },
  },
  {
    id: "berserker.hemorrhage",
    classId: "berserker",
    tier: "hybrid",
    name: "Hemorrhage",
    description: "An enemy that is both burning and bleeding when it dies explodes, spreading both to everything nearby.",
    flavor: "Two problems, one solution, wide blast radius.",
    requires: [
      { path: "Bloodletter", points: 3 },
      { path: "Inferno", points: 3 },
    ],
    effects: [
      { kind: "rule", rule: "berserker.hybrid.hemorrhage" },
      {
        kind: "grantEffect",
        on: { event: "enemyDeath" },
        effects: [
          { kind: "spreadStatus", status: "bleed", radius: 120, to: "target" },
          { kind: "spreadStatus", status: "burn", radius: 120, to: "target" },
          { kind: "damage", damage: { base: 1.6, scale: "attack", type: "fire", channel: "execute" }, to: "enemies" },
        ],
      },
    ],
    ui: { badge: "HEM" },
  },
  {
    id: "berserker.deathblow",
    classId: "berserker",
    tier: "hybrid",
    name: "Deathblow",
    description: "Below a third health, heavy attacks consume a chunk of your remaining health for catastrophic damage.",
    flavor: "Everything you have, on one swing.",
    requires: [
      { path: "Last Breath", points: 3 },
      { path: "Marauder", points: 3 },
    ],
    effects: [{ kind: "rule", rule: "berserker.hybrid.deathblow" }],
    mutations: [
      {
        id: "deathblow.heavy",
        label: "heavy attacks spend health for damage",
        target: { withAllTags: ["melee", "heavy"] },
        ops: [{ kind: "damagePacket", scaleBase: 1.4, addExecuteMissingHealth: 0.15 }],
      },
    ],
    ui: { badge: "DBL" },
  },
  {
    id: "berserker.butchers_rhythm",
    classId: "berserker",
    tier: "hybrid",
    name: "Butcher's Rhythm",
    description: "Kills refund heavy-attack cooldowns directly, not just the last-used skill.",
    flavor: "The axe never really stops.",
    requires: [
      { path: "Marauder", points: 3 },
      { path: "Predator", points: 3 },
    ],
    effects: [
      { kind: "rule", rule: "berserker.hybrid.butchers_rhythm" },
      {
        kind: "mutate",
        mutation: {
          id: "butchers_rhythm.cd",
          label: "heavy skills recover on kill",
          target: { withTag: "heavy" },
          ops: [{ kind: "cooldown", scale: 0.8 }],
        },
      },
    ],
    ui: { badge: "BRH" },
  },
  {
    id: "berserker.wildfire",
    classId: "berserker",
    tier: "hybrid",
    name: "Wildfire",
    description: "A burning kill escalates Inferno Rush: each one in a row makes the next fire zone bigger and hotter.",
    flavor: "It was going to spread anyway.",
    requires: [
      { path: "Inferno", points: 3 },
      { path: "Predator", points: 3 },
    ],
    effects: [
      { kind: "rule", rule: "berserker.hybrid.wildfire" },
      {
        kind: "grantEffect",
        on: { event: "kill" },
        effects: [{ kind: "zone", zone: { radius: 80, duration: 4, tickInterval: 0.5, follows: false, mergeable: true, damage: { base: 0.4, scale: "attack", type: "fire", channel: "periodic" }, status: { id: "burn", chance: 1 } } }],
      },
    ],
    ui: { badge: "WLD" },
  },
  {
    id: "berserker.rupture",
    classId: "berserker",
    tier: "hybrid",
    name: "Rupture",
    description: "Heavy attacks consume every Bleed stack on the target for an immediate physical detonation.",
    flavor: "Cash it all in.",
    requires: [
      { path: "Bloodletter", points: 3 },
      { path: "Marauder", points: 3 },
    ],
    effects: [{ kind: "rule", rule: "berserker.hybrid.rupture" }],
    mutations: [
      {
        id: "rupture.heavy",
        label: "heavy attacks rupture bleeds",
        target: { withTag: "heavy" },
        ops: [
          {
            kind: "addEffect",
            at: "end",
            effects: [{ kind: "consumeStatus", status: "bleed", to: "target", then: [{ kind: "damage", damage: { base: 2.5, scale: "attack", type: "physical", channel: "execute" }, to: "enemies" }] }],
          },
        ],
      },
    ],
    ui: { badge: "RPT" },
  },
  {
    id: "berserker.blood_god",
    classId: "berserker",
    tier: "mythic",
    name: "Blood God",
    description:
      "Worldbreaker's finale never ends: while you are below half health it becomes a standing aura that bleeds, burns and re-detonates everything around you, fed by your own missing health.",
    flavor: "You stopped being a person a few floors ago.",
    requires: [
      { path: "Bloodletter", points: 6 },
      { path: "Last Breath", points: 4 },
      { path: "Inferno", points: 4 },
    ],
    effects: [{ kind: "rule", rule: "berserker.mythic.blood_god" }],
    mutations: [
      {
        id: "blood_god.worldbreaker",
        label: "Worldbreaker → Blood God",
        target: { abilityId: "berserker.worldbreaker" },
        ops: [
          { kind: "damagePacket", scaleBase: 1.2, addExecuteMissingHealth: 0.1 },
          {
            kind: "addEffect",
            at: "end",
            effects: [
              {
                kind: "zone",
                zone: {
                  radius: 150,
                  duration: 10,
                  tickInterval: 0.5,
                  follows: true,
                  mergeable: false,
                  damage: { base: 0.6, scale: "attack", type: "fire", channel: "periodic" },
                  status: { id: "bleed", chance: 1 },
                },
              },
            ],
          },
          { kind: "addTags", tags: ["aura"] },
        ],
      },
    ],
    ui: { badge: "GOD" },
  },
];

// --- the assembled class -------------------------------------------

export const BERSERKER: PilotClass = {
  classId: "berserker",
  name: "Berserker",
  fantasy: "The fighter who turns pain, missing health, Rage, Bleed and raw brutality into damage.",
  role: "Bruiser / melee DPS / aggressive sustain.",
  question: "How much pain can I turn into power?",
  resources: BERSERKER_RESOURCES,
  statuses: BERSERKER_STATUSES,
  abilities: BERSERKER_ABILITIES,
  progression: BERSERKER_PROGRESSION,
  unlocks: BERSERKER_UNLOCKS,
};
